### ISSUE TITLE
Support for proxy

### ISSUE THREAD

**Issue by akstron** [ContriHUB/E-CP#11]
Currently the CPI tool does not supports proxy. Add commands to setup and use proxy.

**Comment by ashutoshsuthar2020** [comment]
Can i have on this issue, i have added support for proxy

**Comment by akstron** [comment]
Kindly open a pull request for the same.

**Comment by ashutoshsuthar2020** [comment]
I tried to do that but it showed the repo have moved 13 commits forward ,while update my local repo the program have failed to run "ecp problem https://codeforces.com/contest/1739/problem/A ." can you please look into this.

**Comment by ashutoshsuthar2020** [comment]
I have requested a pr for the same now.

**Comment by ashutoshsuthar2020** [comment]
> Kindly open a pull request for the same.

Sir can you check it now, deadline is approaching for the pr.

**Comment by ashutoshsuthar2020** [comment]
https://github.com/ContriHUB/E-CP/pull/19 sir look for this issue i think the link is wrong on contrihub

**Comment by ashutoshsuthar2020** [comment]
Sir can you see it now, i have made a PR.

**Comment by akstron** [comment]
Done
