### ISSUE TITLE
Unexpected input file found

### ISSUE THREAD

**Issue by akstron** [ContriHUB/E-CP#27]
Creating this problem 'https://codeforces.com/contest/1736/problem/A' gives wrong input file.

**Comment by utkarsh1236** [comment]
Hi @akstron ! Can you assign this issue to me?

**Comment by utkarsh1236** [comment]
Hi @akstron! This issue is currently not available on the ContriHUB website. As of now issue #27 on the website is [this](https://github.com/ContriHUB/ContriHUB-22/issues/27). So could you please tell where can I request assignment?

**Comment by akstron** [comment]
@utkarsh1236 Kindly check issue #28 now.
