### ISSUE TITLE
Pick up random codeforces problem in test session

### ISSUE THREAD

**Issue by akstron** [ContriHUB/E-CP#6]
Add a feature to pick up random codeforces problem for practice while starting a test session.

**Comment by DNA5769** [comment]
Could you elaborate more on what we should do for this issue, like should we make a new test command which just outputs a random codeforces problem on the console or do you expect something else.

**Comment by akstron** [comment]
Actually we first need to link our codeforces account with the cli tool and then pick random codeforces problem ( which is not attempted by the user) according to the input difficultly level. Closing this issue as of now. Issue will be raised again once connecting with codeforces account feature is developed.

**Comment by DNA5769** [comment]
Ok sir thanks

**Comment by DNA5769** [comment]
Sir can you give me this issue. I will complete #9  as well

**Comment by akstron** [comment]
#9 is assigned to someone else

**Comment by DNA5769** [comment]
Oh ok cool
