### ISSUE TITLE
Add validation when changing default template

### ISSUE THREAD

**Issue by akstron** [ContriHUB/E-CP#7]
The file path for default template must be a text file. Add validations for it.

**Comment by Dadaji18** [comment]
I would like to work on this issue.

**Comment by Dadaji18** [comment]
Can you please update me on this issue?

**Comment by akstron** [comment]
Sorry for delay. File extensions might not suggest the actual content right. It can be .cpp, .py, .java, .txt etc.

**Comment by akstron** [comment]
Resolved
